defmodule AnsiHelper do
  alias IO.ANSI

  @colors []
  defguard is_color(maybe_color) when is_atom(maybe_color) and maybe_color in @colors

  def do_color(color) when is_binary(color), do: do_color(String.to_atom(color))
  def do_color(color) when is_color(color) do
    apply(ANSI, color, [])
  end

  @colors [
    :black,
    :black_background,
    :blink_off,
    :blink_rapid,
    :blink_slow,
    :blue,
    :blue_background,
    :bright,
    :clear,
    :clear_line,
    :color,
    :color,
    :color_background,
    :color_background,
    :conceal,
    :crossed_out,
    :cursor,
    :cursor_down,
    :cursor_down,
    :cursor_left,
    :cursor_left,
    :cursor_right,
    :cursor_right,
    :cursor_up,
    :cursor_up,
    :cyan,
    :cyan_background,
    :default_background,
    :default_color,
    :enabled?,
    :encircled,
    :faint,
    :font_1,
    :font_2,
    :font_3,
    :font_4,
    :font_5,
    :font_6,
    :font_7,
    :font_8,
    :font_9,
    :format,
    :format,
    :format_fragment,
    :format_fragment,
    :framed,
    :green,
    :green_background,
    :home,
    :inverse,
    :inverse_off,
    :italic,
    :light_black,
    :light_black_background,
    :light_blue,
    :light_blue_background,
    :light_cyan,
    :light_cyan_background,
    :light_green,
    :light_green_background,
    :light_magenta,
    :light_magenta_background,
    :light_red,
    :light_red_background,
    :light_white,
    :light_white_background,
    :light_yellow,
    :light_yellow_background,
    :magenta,
    :magenta_background,
    :no_underline,
    :normal,
    :not_framed_encircled,
    :not_italic,
    :not_overlined,
    :overlined,
    :primary_font,
    :red,
    :red_background,
    :reset,
    :reverse,
    :reverse_off,
    :underline,
    :white,
    :white_background,
    :yellow,
    :yellow_background
  ]
end